# Generated by Django 4.0.4 on 2022-12-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_comments_allowed',
            field=models.BooleanField(default=True, help_text='By default posts should have comments'),
        ),
    ]
