# Generated by Django 4.0.4 on 2022-12-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_post_is_comments_allowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postMedia',
        ),
        migrations.AddField(
            model_name='post',
            name='imageUrl',
            field=models.ImageField(blank=True, null=True, upload_to='postImages'),
        ),
        migrations.AddField(
            model_name='post',
            name='videoUrl',
            field=models.ImageField(blank=True, null=True, upload_to='postVideo'),
        ),
    ]
