# Generated by Django 4.0.4 on 2022-12-09 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_post_postmedia_post_imageurl_post_videourl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='videoUrl',
        ),
    ]
