# Generated by Django 4.0.4 on 2022-12-09 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_post_videourl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='video',
        ),
    ]
